// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxR3_6wsLe2r6an3xW160GaXlL-v13FsA',
    appId: '1:834707577867:web:8a877f3ac91282f63fbb0e',
    messagingSenderId: '834707577867',
    projectId: 'fire-learn-5388f',
    authDomain: 'fire-learn-5388f.firebaseapp.com',
    storageBucket: 'fire-learn-5388f.firebasestorage.app',
    measurementId: 'G-KBCR6E7NDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsBAnpYIXtCm2OEptv8czE8P3z_rKLVdY',
    appId: '1:834707577867:android:7ab93b05933b37b53fbb0e',
    messagingSenderId: '834707577867',
    projectId: 'fire-learn-5388f',
    storageBucket: 'fire-learn-5388f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3B2YlePw5ENmhFop2weOrrUrapwdUDa8',
    appId: '1:834707577867:ios:835752d51842ec1e3fbb0e',
    messagingSenderId: '834707577867',
    projectId: 'fire-learn-5388f',
    storageBucket: 'fire-learn-5388f.firebasestorage.app',
    androidClientId: '834707577867-qqk3q2266bsp0vf0huq4o2m1m5fk34ge.apps.googleusercontent.com',
    iosClientId: '834707577867-ndgglnqa6oqnbs0brcjnog3vl00oq5g8.apps.googleusercontent.com',
    iosBundleId: 'com.example.marketly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3B2YlePw5ENmhFop2weOrrUrapwdUDa8',
    appId: '1:834707577867:ios:835752d51842ec1e3fbb0e',
    messagingSenderId: '834707577867',
    projectId: 'fire-learn-5388f',
    storageBucket: 'fire-learn-5388f.firebasestorage.app',
    androidClientId: '834707577867-qqk3q2266bsp0vf0huq4o2m1m5fk34ge.apps.googleusercontent.com',
    iosClientId: '834707577867-ndgglnqa6oqnbs0brcjnog3vl00oq5g8.apps.googleusercontent.com',
    iosBundleId: 'com.example.marketly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxR3_6wsLe2r6an3xW160GaXlL-v13FsA',
    appId: '1:834707577867:web:6fec29a70c4dcedd3fbb0e',
    messagingSenderId: '834707577867',
    projectId: 'fire-learn-5388f',
    authDomain: 'fire-learn-5388f.firebaseapp.com',
    storageBucket: 'fire-learn-5388f.firebasestorage.app',
    measurementId: 'G-8NE8CH6E89',
  );
}
